name: silid
description: "Silid: A cross-platform educational booking and conference app for private tutors."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_icon_snackbar: ^1.2.1
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.3
  get: ^4.7.2
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_identity_services_web: ^0.3.3
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/SILID.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/SILID.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icons/SILID.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/SILID.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google_icon.png
    - assets/icons/teacher.png
    - assets/icons/student.png
    - assets/icons/SILID_transparent.png
    - assets/icons/SILID.png
