// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChXslc2BYqoCS4okpr9Rf2lltpBPT4LqA',
    appId: '1:16804108720:web:215341b5fb95adcd2c9e75',
    messagingSenderId: '16804108720',
    projectId: 'silid-b01f6',
    authDomain: 'silid-b01f6.firebaseapp.com',
    storageBucket: 'silid-b01f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk7LvvGEIkMcrm3PnARPoxiq2sAL2okyI',
    appId: '1:16804108720:android:56a7a6b4a5336a0c2c9e75',
    messagingSenderId: '16804108720',
    projectId: 'silid-b01f6',
    storageBucket: 'silid-b01f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyE3IRmxSXyoT5QOSSxoQQcj4abDi0YpI',
    appId: '1:16804108720:ios:485729db8ea68f3a2c9e75',
    messagingSenderId: '16804108720',
    projectId: 'silid-b01f6',
    storageBucket: 'silid-b01f6.firebasestorage.app',
    iosBundleId: 'com.example.silid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyE3IRmxSXyoT5QOSSxoQQcj4abDi0YpI',
    appId: '1:16804108720:ios:485729db8ea68f3a2c9e75',
    messagingSenderId: '16804108720',
    projectId: 'silid-b01f6',
    storageBucket: 'silid-b01f6.firebasestorage.app',
    iosBundleId: 'com.example.silid',
  );
}
